services:
  - type: web
    name: execution-coach-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: execution-bot-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.0
    autoDeploy: true

databases:
  - name: execution-bot-db
    databaseName: execution_coach
    user: bot_user
    region: ohio
    plan: free